spring:
  datasource:
    url: jdbc:mysql://192.168.1.12:3306/customer-consumer?serverTimezone=UTC
    username: customer-consumer
    password: hoilamgi
    # Enables execution of data-mysql.sql script
    platform: MYSQL
    # Not required as we dont need to initialize dummy data in persistant database
    # Uncomment this when the database is recreated so dummy data is added. Comment it afterwards
    # initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    
    ROOT: info
    # debug level for all use defined code logs
    com.cg: info
# Disables discovery CLient eatures - Use this or Confi file
eureka:
  client:
    enabled: true
