server:
  port: ${server_port:9820}
spring:
  profiles:
    active: mysql
  application:
    name: inventory-patient-service
eureka:
  client:
    serviceUrl:
      # Changed because previous once was ausing errors with gateway
      defaultZone: ${eureka_url:http://localhost:8761/eureka/}

# JTW Config
security:
  jwt:
    token:
      secret-key: secret-key-nguyen-tuan-hung-dep-trai-vai
      expire-length: 30000000 # 5 minutes duration by default: 5 minutes * 60 seconds * 1000 miliseconds
